from pathlib import Path
import json,html,textwrap
R=Path(__file__).resolve().parents[1]
story=json.loads((R/'source/story.json').read_text())
esc=html.escape

def sparkle(size=50):
 return f'<svg width="{size}" height="{size}" viewBox="0 0 100 100" fill="none"><path d="M50 4 Q54 43 96 50 Q55 55 50 96 Q45 55 4 50 Q44 45 50 4Z" fill="currentColor"/></svg>'
def tick():return '<svg viewBox="0 0 24 24" width="27" height="27" fill="none"><path d="m5 12 4 4 10-10" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/></svg>'
def chip(label='GPU',size=150):
 pins=''.join(f'<path d="M{v} 10v15 M{v} 125v15 M10 {v}h15 M125 {v}h15"/>' for v in [45,65,85,105])
 return f'<svg width="{size}" height="{size}" viewBox="0 0 150 150" fill="none"><g stroke="currentColor" stroke-width="2.3">{pins}<rect x="25" y="25" width="100" height="100" rx="16"/><rect x="38" y="38" width="74" height="74" rx="6"/></g><text x="75" y="85" text-anchor="middle" fill="currentColor" font-family="Arial" font-size="27" font-weight="700">{label}</text></svg>'
def icon(kind):
 paths={
 'plan':'<rect x="19" y="15" width="42" height="51" rx="5"/><path d="M29 29h22M29 40h22M29 51h14"/>',
 'critic':'<path d="M17 18h46v33H42L28 65V51H17z"/><path d="M32 29c0-9 18-9 18 0 0 7-10 5-10 13M40 46v2"/>',
 'code':'<path d="m28 23-17 17 17 17m24-34 17 17-17 17M46 17 34 63"/>',
 'review':'<circle cx="33" cy="34" r="19"/><path d="m47 48 19 19M26 34l5 5 11-12"/>',
 'test':'<path d="M29 13h22M33 13v24L17 62q-3 6 5 6h36q8 0 5-6L47 37V13M26 49h28"/><circle cx="38" cy="56" r="2"/>',
 'cloud':'<path d="M19 58h43c18-1 15-28-2-29C56 8 25 8 22 32 3 30 3 59 19 58z"/>',
 'human':'<circle cx="40" cy="25" r="12"/><path d="M17 68v-7c0-26 46-26 46 0v7M24 48l16 13 16-13"/>',
 'branch':'<circle cx="23" cy="17" r="6"/><circle cx="57" cy="20" r="6"/><circle cx="23" cy="65" r="6"/><path d="M23 23v36M57 26c0 24-34 8-34 28"/>',
 'coffee':'<path d="M16 27h40v25c0 18-40 18-40 0zM56 32h6c20 0 20 19-6 19M22 16v-7M36 16v-7M49 16v-7M10 72h54"/>'}
 return f'<svg viewBox="0 0 80 80" width="72" height="72" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round">{paths[kind]}</svg>'
def label(t,cls=''):return f'<div class="eyebrow {cls}">{t}</div>'
def pill(t,cls=''):return f'<span class="pill {cls}">{t}</span>'
def note(t,cls=''):return f'<div class="note {cls}">{t}</div>'
def frame(path,cls='',labeltxt=''):
 return f'<div class="micro-frame {cls}"><img src="assets/{path}" alt="Synthetic microscopy illustration"/>{f"<span>{labeltxt}</span>" if labeltxt else ""}<i class="corner a"></i><i class="corner b"></i><i class="corner c"></i><i class="corner d"></i></div>'

sc=[]
# INTRO
stack=''.join(frame(f'frame-{i}.png',f'stack-frame sf{i}',f'FRAME {i+1:02d}') for i in range(4))
sc.append(f'''<div class="hero-layout"><div class="hero-copy">{label('A SCIENCE HACKATHON STORY','reveal')}
<h1 class="hero-title"><span class="reveal">MOTION,</span><span class="reveal blue">CORRECTED.</span></h1>
<p class="hero-deck reveal">Faster science.<br class="deliberate"> More agents than expected.</p>
<div class="partner-inline reveal">STFC <b>×</b> Google <b>×</b> PA</div>
</div><div class="stack-space reveal">{stack}<div class="stack-label">FRAME ALIGNMENT / SCHEMATIC</div></div></div>
{note('We also delegated<br class="deliberate">the presentation.','intro-note reveal')}''')
# MICROSCOPY
sc.append(f'''<h2 class="reveal">Tiny particles. <span class="blue">Big workload.</span></h2>
<div class="compare-layout"><div class="compare-col reveal">{label('BEFORE / UNALIGNED SUM')}{frame('micrograph-unaligned.png','unaligned','MOTION BLUR')}<p>Signal, spread out.</p></div><div class="compare-arrow reveal">→</div><div class="compare-col reveal">{label('AFTER / ALIGNED SUM')}{frame('micrograph-aligned.png','aligned','FRAME SHIFTS CORRECTED')}<p>Signal, working together.</p></div></div>
<div class="source reveal">Synthetic illustration of motion correction, not an experimental output comparison.</div>''')
# ALGORITHM
steps=[('01','ESTIMATE',frame('correlation.png','mini-frame'), 'Find the shift','FFT + cross-correlation'),('02','ALIGN',frame('frame-3.png','mini-frame moving-frame'),'Undo the motion','Global + local trajectories'),('03','WEIGHT','<div class="spectrum">'+''.join(f'<i style="height:{25+90*(1-i/15)**1.5}px"></i>' for i in range(15))+'</div>','Account for dose','Frequency-dependent weights'),('04','COMBINE',frame('micrograph-aligned.png','mini-frame'),'Build the image','Corrected micrograph')]
sc.append('<h2 class="reveal">Find the drift. <span class="blue">Undo the drift.</span></h2><div class="algorithm">'+''.join(f'<div class="step reveal" id="step{i}"><div class="step-head"><b>{a}</b>{b}</div>{g}<h3>{t}</h3><p>{s}</p></div>'+('<div class="step-arrow reveal">→</div>' if i<3 else '') for i,(a,b,g,t,s) in enumerate(steps))+'</div><div class="algorithm-bottom reveal"><span>Frames</span><div class="flowline"><i></i></div><span>Useful signal</span></div><div class="source reveal">Algorithm schematic. The challenge is preserving scientific behaviour while changing the compute path.</div>')
# THREE ROUTES
sc.append(f'''<h2 class="reveal">One challenge. <span class="blue">Three routes.</span></h2>
<div class="routes"><div class="origin reveal">{chip('CPU',155)}<h3>RELION-derived</h3><p>Standalone motion correction</p>{pill('REFERENCE FIRST')}</div>
<svg class="route-lines" viewBox="0 0 420 520" fill="none"><g stroke="#4285F4" stroke-width="3"><path d="M0 260h110V95h300"/><path d="M0 260h410"/><path d="M110 260v165h300"/></g><circle class="route-pulse" cx="110" cy="260" r="8" fill="#A8C7FA"/></svg>
<div class="route-targets"><div class="route reveal"><div class="route-code">CUDA</div><p>NVIDIA compute kernels</p></div><div class="route reveal"><div class="route-code">JAX</div><p>Array-computing exploration</p></div><div class="route reveal"><div class="route-code">METAL</div><p>Apple silicon compute</p></div></div></div>
<div class="source reveal">CUDA: #16–17 · JAX: #14–15 · Metal: #29–35. Parallel workstreams at different stages of maturity.</div>''')
# ANTIGRAVITY
sc.append(f'''<div class="title-pair"><h2 class="reveal">Antigravity.</h2><p class="serif reveal">Very down-to-earth work.</p></div>
<div class="workspace reveal"><div class="windowbar"><span class="traffic"><i></i><i></i><i></i></span><b>MotionCorr / hackathon workspace</b><span>WORKFLOW ILLUSTRATION</span></div>
<div class="workspace-body"><div class="task-list"><div class="eyebrow">THE ITERATION LOOP</div>'''+''.join(f'<div class="task" id="task{i}"><span class="task-index">{i+1:02d}</span><span>{t}</span><span class="taskcheck">{tick()}</span></div>' for i,t in enumerate(['Understand the engine','Profile the real workload','Implement a bounded change','Run the reference checks']))+f'''</div><div class="prompt-area">{sparkle(46)}<div class="eyebrow">OUR BRIEF</div><p>Accelerate motion correction.<br class="deliberate"><span class="blue">Keep the science honest.</span></p><div class="code-chips">{pill('alignPatch()')}{pill('realSpaceInterpolation()')}</div><div class="work-log"><span class="blue">→</span> inspect <span>→</span> build <span>→</span> test <span>→</span> refine</div></div></div></div>
{note('Still debugging.<br class="deliberate">Still science.','gravity-note reveal')}
<div class="source reveal">Team experience: extensive use of Google Antigravity for investigation, implementation and iteration.</div>''')
# AGENTS
roles=[('plan','ARCHITECT','Here is the plan.','r0'),('critic','CRITIC','What about the edge cases?','r1'),('code','IMPLEMENT','Small, scoped changes.','r2'),('review','REVIEW','I have a few notes.','r3'),('test','TEST','Show me the outputs.','r4')]
sc.append(f'''<h2 class="reveal">We built a <span class="blue">team of agents.</span></h2><div class="agents-stage"><svg class="agent-links" viewBox="0 0 1728 540" fill="none"><g stroke="#354660" stroke-width="2"><path d="M350 140 864 280 1378 140M420 435 864 280 1308 435M864 70v210"/></g></svg>
<div class="human-node reveal">{icon('human')}<b>HUMAN</b><span>Scientific judgment</span></div>'''+''.join(f'<div class="agent {c} reveal"><div class="agent-symbol">{icon(i)}</div><div><h3>{r}</h3><p>{q}</p></div></div>' for i,r,q,c in roles)+f'''<div class="agent-brand reveal">{sparkle(30)} Gemini Enterprise workflow</div></div>
<div class="source reveal">Agent roles adapted from presentation/AGENTIC_LIFECYCLE.md. The dialogue is a dramatisation.</div>''')
# WORKFLOW
flow=[('branch','ISSUE','Label-gated task'),('cloud','CLOUD RUN','Scheduled worker'),('critic','GEMINI','Triage · fix · review'),('code','DRAFT PR','Bounded proposal'),('human','HUMAN','Final decision')]
sc.append(f'''<h2 class="reveal">Automation. <span class="blue">Human merge button.</span></h2><div class="cloud-flow">'''+''.join(f'<div class="flow-node reveal" id="fn{i}"><div class="flow-icon">{icon(ic)}</div><h3>{t}</h3><p>{su}</p></div>'+('<div class="flow-arrow reveal">→</div>' if i<4 else '') for i,(ic,t,su) in enumerate(flow))+f'''</div><div class="guardrails reveal">{pill('SCOPED CHANGES')}{pill('EXPLICIT CHECKS')}{pill('NO AUTO-MERGE','green-outline')}</div>
<div class="source reveal">PR #1: Gemini-powered issue triage, draft fixes and PR review on Google Cloud. Human approval remains separate.</div>''')
# REPRO
tiles=''.join(f'<div class="movie-tile" id="movie{i}"><span>{i+1:02d}</span>{tick()}</div>' for i in range(24))
sc.append(f'''<h2 class="reveal">Make it <span class="blue">repeatable first.</span></h2><div class="repro-grid"><div class="repro-stat"><div class="stat-number reveal">24<span>/24</span></div><h3 class="reveal">tutorial movies</h3><div class="thread-compare reveal">CPU <b>1 thread</b><span>↔</span>CPU <b>4 threads</b></div><p class="reveal">Exact agreement for the fixed standalone CPU.</p></div><div class="movie-matrix reveal">{tiles}</div></div>
{note('Same movie.<br class="deliberate">Same answer.','repro-note reveal')}
<div class="source reveal">PR #23: fixed standalone CPU, 1 versus 4 threads. This is not a claim of unchanged outputs versus upstream RELION.</div>''')
# TESTS
sc.append(f'''<h2 class="reveal">The tests <span class="blue">had notes.</span></h2><div class="gates-layout"><div class="synthetic-gate reveal"><div class="eyebrow">CUDA / SYNTHETIC GLOBAL ALIGNMENT</div><div class="gate-count">2<span>/2</span></div><h3>Small fixtures pass.</h3><div class="gate-fixtures"><span>{tick()} Integer shifts</span><span>{tick()} Subpixel shifts</span></div></div><div class="experimental-gate reveal"><div class="eyebrow">CUDA / 24 EXPERIMENTAL MOVIES</div><h3>Image differences remain.</h3>{pill('EXPERIMENTAL · GATE NOT MET','warning')}
<div class="gate-chart"><div class="gate-limit"><b>0.001</b><span>unchanged limit</span></div><div class="observed-range"><b>0.0029–0.0101</b><span>reported relative image RMSE</span></div><div class="gate-axis"></div></div><div class="test-equation">It runs <b>≠</b> it passes.</div></div></div>
<div class="source reveal">PR #28: two small synthetic fixtures. PR #25: the separate experimental corrected-image Gate 2 remained unmet.</div>''')
# BOTTLENECK
sc.append(f'''<h2 class="reveal">Fast kernel. <span class="blue">Same queue.</span></h2><div class="bottleneck-stage"><div class="benchmark-chart reveal"><div class="eyebrow">WHOLE-MOVIE WALL TIME / LOWER IS BETTER</div><div class="bench-row"><span>CPU</span><div class="bar-wrap"><div class="bench-bar cpu-bar"></div></div><b>15.66 s</b></div><div class="bench-row"><span>GPU-assisted</span><div class="bar-wrap"><div class="bench-bar cuda-bar"></div></div><b>16.38 s</b></div><div class="bottleneck-insight">Fast patch kernels.<br class="deliberate"><strong>CPU-bound reconstruction.</strong></div></div><div class="ratio reveal"><div>0.96<span>×</span></div><p>Whole-movie speed ratio</p>{note('The bottleneck moved.<br class="deliberate">It did not retire.','inline-note')}</div></div>
<div class="source reveal">PR #37: A100, 8 CPU threads, five isolated runs per path; medians. A patch-alignment prototype, not the later reconstruction PR.</div>''')
# NEW STAGE
sc.append(f'''<h2 class="reveal">Follow the <span class="blue">bottleneck.</span></h2><div class="new-result"><div class="new-stat reveal"><div class="eyebrow">EARLY RECONSTRUCTION-STAGE REPORT</div><div class="large-speed">29.5<span>×*</span></div><p><span>10.5 s</span><b>→</b><strong>0.356 s</strong></p></div><div class="streaming-diagram reveal"><div class="stream-frames">'''+''.join(f'<div class="stream-frame stf{i}">{i+1:02d}</div>' for i in range(5))+f'''</div><div class="stream-arrow">→</div><div class="stream-gpu">{chip('GPU',168)}<span>One frame<br class="deliberate">at a time</span></div><div class="stream-arrow">→</div><div class="stream-sum">Σ<span>SUM</span></div><div class="stream-label">STREAMING RECONSTRUCTION</div></div></div>
<div class="stat-disclaimer reveal">* Reconstruction stage only. Preliminary report in open PR #45, not a whole-movie speedup.</div>
{note('This asterisk<br class="deliberate">is doing real work.','asterisk-note reveal')}
<div class="source reveal">PR #45 is an experimental proposal. Full-pipeline numerical acceptance and performance remain separate checks.</div>''')
# PROGRESS
sc.append(f'''<h2 class="reveal">Three routes. <span class="blue">Different milestones.</span></h2><div class="milestones"><div class="milestone reveal"><b>CUDA</b><div><h3>Global, patch and reconstruction experiments</h3><p>Working prototypes; numerical differences under investigation</p></div>{pill('EXPERIMENTAL','warning')}</div><div class="milestone reveal"><b>METAL</b><div><h3>Global alignment proposed for Apple silicon</h3><p>Implementation in PR #43; full experimental acceptance pending</p></div>{pill('PROPOSED','blue-outline')}</div><div class="milestone reveal"><b>JAX</b><div><h3>An array-computing exploration track</h3><p>Global shifts, local motion and dose-weighting work packages</p></div>{pill('EXPLORATION')}</div></div><div class="shared-contract reveal">Different backends. <span class="blue">Shared reference tests.</span></div>
<div class="source reveal">Repository snapshot: 24 September 2026. CUDA: #25/#37/#45 · Metal: #43 · JAX: issues #14–15.</div>''')
# LESSONS
sc.append(f'''<h2 class="reveal">Faster iteration. <span class="blue">Better questions.</span></h2><div class="lessons"><div class="lesson lesson0"><b>SCOPE.</b><p>A task an agent can actually finish.</p></div><div class="lesson lesson1"><b>MEASURE.</b><p>A test that can disagree with the story.</p></div><div class="lesson lesson2"><b>REVIEW.</b><p>A human who understands the science.</p></div></div><div class="snack reveal">{icon('coffee')}<span>Human responsibilities:<br class="deliberate">judgment + snacks.</span></div>
<div class="source reveal">Hackathon lessons: Google Antigravity for iteration, independent checks for evidence, humans for scientific decisions.</div>''')
# VIDEO
sc.append(f'''<div class="meta-layout"><div class="meta-copy"><div class="eyebrow reveal">ONE FINAL ISSUE</div><h2 class="meta-title reveal">And yes.<br class="deliberate">We delegated<br class="deliberate"><span class="blue">the video.</span></h2><div class="chat joke1"><span>AGENT</span><p>Can I skip validation?</p></div><div class="chat joke2"><span>HUMAN</span><p>Not even for the video.</p></div></div><div class="video-task reveal"><div class="video-task-head">PRESENTATION TASK <span>03:00</span></div><div class="mini-film"><span class="mini-kicker">STFC × GOOGLE × PA</span><b>MOTION,<br class="deliberate"><span>CORRECTED.</span></b><div class="mini-play">▶</div></div><div class="edit-tracks"><div class="edit-track"><b>STORY</b><i></i><i></i><i></i></div><div class="edit-track"><b>VISUALS</b><i></i><i></i><i></i><i></i></div><div class="edit-track"><b>CAPTIONS</b><i></i><i></i><i></i></div><span class="playhead"></span></div><div class="video-deliverable">GPU prototypes. Reusable agents. Tougher tests.</div></div></div>
<div class="source reveal">A three-minute hackathon story. The agent dialogue is a dramatisation, not a quotation from an actual review.</div>''')
# END
sc.append(f'''<div class="endcard"><div class="end-mark reveal">{sparkle(66)}</div><h1 class="end-title reveal">MOTION,<br class="deliberate"><span class="blue">CORRECTED.</span></h1><div class="end-tag reveal">HYPE, TESTED.</div><div class="end-partners reveal">STFC <b>×</b> Google <b>×</b> PA</div><div class="end-tools reveal">GOOGLE ANTIGRAVITY · GEMINI ENTERPRISE · GOOGLE CLOUD</div></div>''')

css=r'''
@font-face{font-family:InterDisplay;src:local('Inter Display');font-weight:400}
@font-face{font-family:InterDisplay;src:local('Inter Display Medium');font-weight:500}
@font-face{font-family:InterDisplay;src:local('Inter Display SemiBold');font-weight:600}
@font-face{font-family:InterDisplay;src:local('Inter Display Bold');font-weight:700 750}
@font-face{font-family:InterDisplay;src:local('Inter Display ExtraBold');font-weight:800 900}
@font-face{font-family:InterLocal;src:local('Inter');font-weight:100 900}
:root{--bg:#111722;--fg:#F5F2EB;--blue:#A8C7FA;--active:#4285F4;--muted:#99A6BA;--line:#35425A;--yellow:#FBBC04;--red:#EA4335;--green:#34A853}
*{box-sizing:border-box}html,body{width:1920px;height:1080px;margin:0;padding:0;overflow:hidden;background:var(--bg);color:var(--fg);font-family:InterDisplay,InterLocal,Arial,sans-serif}body{-webkit-font-smoothing:antialiased}#film{position:relative;width:100%;height:100%;overflow:hidden;background:var(--bg)}
.scene{position:absolute;inset:0}.scene-inner{position:absolute;inset:0;background:var(--bg);overflow:hidden}.scene-content{width:100%;height:100%;padding:156px 96px 188px;display:flex;flex-direction:column;gap:28px;position:relative;z-index:2}
.scene-bg{position:absolute;inset:0;overflow:hidden;background:radial-gradient(ellipse at 86% 28%,#1B2B43 0%,#111722 56%)}.grid-lines{position:absolute;inset:-100px;background-image:linear-gradient(#7186A80B 1px,transparent 1px),linear-gradient(90deg,#7186A80B 1px,transparent 1px);background-size:84px 84px;transform:rotate(-5deg)}.orbital{position:absolute;width:930px;height:930px;border:1px solid #A8C7FA0A;border-radius:50%;right:-300px;top:-330px}.orbital:after{content:'';position:absolute;inset:70px;border:1px solid #A8C7FA0C;border-radius:50%}.bg-plus{position:absolute;color:#7186A822;font:24px monospace}.noise-line{position:absolute;inset:0;background:repeating-linear-gradient(0deg,transparent 0 4px,#11172213 4px 5px);opacity:.35;pointer-events:none}
h1,h2,h3,p{margin:0}h2{font-size:85px;line-height:1.06;letter-spacing:-4px;font-weight:750;max-width:1730px;flex-shrink:0}h3{font-size:34px;line-height:1.2;letter-spacing:-.6px}p{line-height:1.35}.blue{color:var(--blue)}.serif{font-family:Georgia,serif;font-style:italic}.eyebrow{font-size:24px;line-height:1.25;letter-spacing:2.8px;font-weight:650;color:var(--muted)}.pill{display:inline-flex;align-items:center;justify-content:center;padding:12px 20px;border:1px solid #53617A;border-radius:40px;font-size:21px;letter-spacing:1.1px;line-height:1.2;white-space:nowrap;color:var(--fg);background:#172130}.green-outline{border-color:#57C77A;color:#9AE8B0}.blue-outline{border-color:var(--active);color:var(--blue)}.warning{background:#FBBC0411;border-color:#C89606;color:#FFD765}
.note{background:#FBBC04;color:#29230E;font-family:Georgia,serif;font-size:35px;line-height:1.12;font-style:italic;padding:21px 28px 23px;border-radius:4px;box-shadow:0 12px 24px #0003;transform:rotate(-4deg);width:max-content}.note:before{content:'';position:absolute;width:72px;height:17px;background:#F5F2EB55;left:calc(50% - 36px);top:-7px}.source{font-size:23px;line-height:1.32;color:#AEBACB;position:absolute;left:96px;right:96px;bottom:168px;min-height:32px;letter-spacing:.1px}
.header{position:absolute;z-index:100;left:96px;right:96px;top:58px;display:flex;align-items:center;justify-content:space-between}.brand{display:flex;align-items:center;gap:15px;color:var(--fg);font-size:22px;font-weight:600;letter-spacing:1.6px}.brandmark{display:flex;gap:5px;align-items:center}.brandmark i{display:block;background:var(--blue);width:5px;height:24px}.brandmark i:nth-child(2){height:34px}.brandmark i:nth-child(3){height:20px}.event{display:flex;gap:18px;align-items:center;font-size:20px;letter-spacing:2px;color:var(--muted)}.g-dots{display:flex;gap:7px}.g-dots i{width:8px;height:8px;border-radius:50%;background:#4285F4}.g-dots i:nth-child(2){background:#EA4335}.g-dots i:nth-child(3){background:#FBBC04}.g-dots i:nth-child(4){background:#34A853}
.chapterline{position:absolute;left:96px;top:115px;z-index:101;font-size:17px;letter-spacing:2.5px;color:#8C9BB1}.chapter{position:absolute;top:0;left:0;width:1728px}.chapter b{position:absolute;right:0;font-weight:500}.progress-track{position:absolute;bottom:25px;left:96px;right:96px;height:3px;background:#344058;z-index:200}.progress-bar{height:100%;background:var(--active);transform-origin:left center}.caption-box{position:absolute;inset:0;z-index:180;pointer-events:none}.caption{position:absolute;left:132px;right:132px;top:930px;height:99px;display:flex;align-items:center;justify-content:center;text-align:center}.caption span{display:block;max-width:1620px;padding:12px 25px 15px;font-size:37px;font-weight:550;line-height:1.24;letter-spacing:-.25px;border-radius:8px;background:#0A101AF5;color:var(--fg);box-shadow:0 0 0 1px #3240567A}
.hero-layout{display:flex;align-items:center;flex:1;gap:38px}.hero-copy{width:1045px;flex-shrink:0;position:relative;z-index:3}.hero-title{font-size:143px;line-height:.98;letter-spacing:-8px;margin-top:30px;font-weight:800}.hero-title span{display:block}.hero-deck{font-size:41px;margin-top:35px;letter-spacing:-1px}.partner-inline{font-size:32px;margin-top:35px;letter-spacing:.5px}.partner-inline b{font-weight:400;color:#62728B;margin:0 15px}.stack-space{width:530px;height:530px;position:relative;perspective:1500px;transform:rotate(-4deg)}.micro-frame{position:relative;border:1px solid #8293AD;border-radius:8px;overflow:hidden;background:#1A2230}.micro-frame img{width:100%;height:100%;object-fit:cover;display:block}.micro-frame>span{position:absolute;left:17px;top:17px;background:#111722DB;padding:8px 11px;font-size:16px;letter-spacing:1.3px}.corner{width:27px;height:27px;position:absolute;border-color:#F5F2EB;border-style:solid;opacity:.8}.corner.a{left:12px;top:12px;border-width:2px 0 0 2px}.corner.b{right:12px;top:12px;border-width:2px 2px 0 0}.corner.c{left:12px;bottom:12px;border-width:0 0 2px 2px}.corner.d{right:12px;bottom:12px;border-width:0 2px 2px 0}.stack-frame{position:absolute;width:460px;height:460px;border-radius:4px;box-shadow:0 14px 35px #0005}.sf0{left:0;top:50px}.sf1{left:22px;top:28px}.sf2{left:44px;top:6px}.sf3{left:66px;top:-16px}.stack-label{position:absolute;left:10px;bottom:-27px;font:18px monospace;letter-spacing:1px;color:var(--muted)}.intro-note{position:absolute;left:1054px;top:764px;font-size:29px;transform:rotate(4deg)}
.compare-layout{display:flex;align-items:center;gap:33px;margin-top:12px;flex:1}.compare-col{flex:1;min-width:0}.compare-col .eyebrow{font-size:22px;margin-bottom:17px}.compare-col .micro-frame{height:440px}.compare-col p{font-size:29px;margin-top:16px;color:#C5CEDD}.compare-arrow{font-size:74px;color:var(--blue);padding:0 2px}.compare-col .micro-frame img{object-position:center}
.algorithm{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-top:48px}.step{width:351px;min-width:0}.step-head{display:flex;align-items:center;gap:17px;font-size:20px;letter-spacing:2px;color:var(--blue);margin-bottom:20px}.step-head b{color:var(--fg);font-size:28px}.mini-frame{width:100%;height:246px;border-color:#4C5F7F}.mini-frame .corner{display:none}.step h3{font-size:33px;margin-top:23px}.step p{font-size:23px;color:var(--muted);margin-top:11px}.step-arrow{color:var(--blue);font-size:42px;margin-top:-20px}.spectrum{height:246px;border:1px solid #4C5F7F;border-radius:8px;display:flex;align-items:center;justify-content:center;gap:8px;padding:34px;background:#172132}.spectrum i{display:block;width:12px;background:var(--blue);border-radius:3px;transform-origin:center}.algorithm-bottom{display:flex;gap:25px;align-items:center;margin:35px 0 0;font-size:24px;color:#C5CEDD}.flowline{height:1px;background:#3C5275;flex:1;position:relative}.flowline i{position:absolute;width:13px;height:13px;background:var(--blue);border-radius:50%;top:-6px;left:0}
.routes{display:flex;align-items:center;gap:0;flex:1;margin-top:15px}.origin{width:480px;min-width:480px;border:1px solid #3D5274;border-radius:22px;padding:42px;text-align:center;background:#162133}.origin svg{color:var(--blue)}.origin h3{font-size:35px;margin:15px 0 10px}.origin p{font-size:23px;color:#B4C3D9;margin-bottom:28px}.route-lines{width:325px;height:495px;flex-shrink:0}.route-targets{display:flex;flex-direction:column;gap:27px;flex:1}.route{display:flex;align-items:center;gap:35px;padding:22px 34px;border:1px solid #3D5274;border-radius:14px;background:#162133;min-height:117px}.route-code{font-weight:800;font-size:54px;letter-spacing:-2px;width:210px;flex-shrink:0}.route p{color:#BECBDD;font-size:28px;max-width:310px}
.title-pair{display:flex;align-items:baseline;gap:37px}.title-pair .serif{font-size:48px;color:#B4C3D9}.workspace{border:1px solid #516381;border-radius:14px;overflow:hidden;margin:28px 24px 0;background:#111B2A}.windowbar{height:62px;border-bottom:1px solid #364862;display:flex;align-items:center;gap:26px;padding:0 28px;font-size:19px;color:#C8D5E9;background:#1A273A}.windowbar>span:last-child{margin-left:auto;font-size:15px;letter-spacing:2px;color:#8395B0}.traffic{display:flex;gap:8px}.traffic i{display:block;border:1px solid #7790B7;width:11px;height:11px;border-radius:50%}.workspace-body{display:flex;height:418px}.task-list{width:550px;border-right:1px solid #344761;padding:31px}.task-list>.eyebrow{font-size:17px;margin-bottom:23px}.task{display:flex;align-items:center;gap:15px;font-size:23px;line-height:1.2;padding:17px 0;border-top:1px solid #2F4059}.task-index{font:17px monospace;color:#8197B9}.taskcheck{margin-left:auto;color:#91D7AD}.prompt-area{padding:35px 48px;position:relative;flex:1}.prompt-area>svg{color:var(--blue);position:absolute;right:34px;top:36px}.prompt-area>.eyebrow{font-size:17px}.prompt-area>p{font-size:36px;margin-top:22px;letter-spacing:-1px;line-height:1.32}.code-chips{display:flex;gap:13px;margin-top:30px}.code-chips .pill{font:17px monospace;letter-spacing:0;border-radius:6px;padding:11px}.work-log{font:19px monospace;display:flex;gap:17px;align-items:center;margin-top:31px;color:#BACAE0}.work-log span{color:#6989B5}.gravity-note{position:absolute;right:146px;top:716px;font-size:30px;transform:rotate(3deg)}
.agents-stage{position:relative;flex:1;min-height:545px}.agent-links{position:absolute;inset:0;width:100%;height:100%}.human-node{position:absolute;left:739px;top:172px;width:250px;height:210px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;background:#17253A;border:1px solid #688BBC;border-radius:28px;box-shadow:0 0 0 12px #1B2A3C66;color:var(--blue)}.human-node b{font-size:28px;letter-spacing:2px}.human-node span{font-size:19px;color:#C3D1E6}.agent{position:absolute;display:flex;align-items:center;gap:20px;background:#182337;border:1px solid #41587A;padding:20px 25px;border-radius:18px;width:420px;min-height:116px}.agent-symbol{color:var(--blue);flex-shrink:0}.agent-symbol svg{width:56px;height:56px}.agent h3{font-size:22px;letter-spacing:2px}.agent p{font-family:Georgia,serif;font-style:italic;font-size:24px;color:#D2DCEE;margin-top:9px}.r0{left:30px;top:86px}.r1{right:30px;top:86px}.r2{left:86px;top:366px}.r3{right:86px;top:366px}.r4{left:659px;top:5px}.agent-brand{position:absolute;bottom:5px;left:654px;display:flex;gap:15px;align-items:center;font-size:23px;color:var(--blue)}
.cloud-flow{display:flex;align-items:center;gap:20px;margin-top:72px}.flow-node{flex:1;min-width:0;text-align:center;min-height:246px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:14px}.flow-icon{width:111px;height:111px;display:flex;justify-content:center;align-items:center;border:1px solid #547297;border-radius:23px;background:#1A2A41;color:var(--blue)}.flow-node:last-child .flow-icon{border-color:#81C995;color:#81C995;background:#193326}.flow-node h3{font-size:28px;letter-spacing:1px}.flow-node p{font-size:23px;color:#BBC8DA}.flow-arrow{font-size:35px;color:#698AB8;margin-top:-56px}.guardrails{display:flex;justify-content:center;gap:32px;margin-top:68px}.guardrails .pill{font-size:24px;padding:16px 30px}
.repro-grid{display:flex;align-items:center;gap:80px;flex:1}.repro-stat{flex:1}.stat-number{font-size:206px;line-height:1;font-weight:800;letter-spacing:-14px}.stat-number span{color:var(--blue);font-size:155px;letter-spacing:-9px}.repro-stat h3{font-size:36px;letter-spacing:-1px;margin-top:14px}.thread-compare{display:flex;gap:13px;align-items:center;font-size:26px;margin-top:44px;white-space:nowrap}.thread-compare b{font-weight:700}.thread-compare>span{color:var(--blue);font-size:40px;margin:0 11px}.repro-stat>p{font-size:25px;margin-top:15px;color:#C5D1E4}.movie-matrix{width:700px;display:grid;grid-template-columns:repeat(6,1fr);gap:16px;margin-top:72px}.movie-tile{height:93px;background:#193629;border:1px solid #548F67;border-radius:9px;display:flex;align-items:center;justify-content:space-between;padding:15px;color:#A0E9B2}.movie-tile span{font:18px monospace;color:#B6D2BE}.movie-tile svg{width:35px;height:35px}.repro-note{position:absolute;right:250px;top:268px;font-size:27px;transform:rotate(4deg)}
.gates-layout{display:flex;gap:82px;flex:1;margin-top:35px}.synthetic-gate{width:555px;flex-shrink:0;border-right:1px solid #344962;padding-right:44px}.synthetic-gate .eyebrow,.experimental-gate .eyebrow{font-size:20px;letter-spacing:1.5px}.gate-count{font-size:166px;font-weight:800;letter-spacing:-10px;line-height:1.1;margin:24px 0;color:#99E5AE}.gate-count span{font-size:115px;color:#70B586}.synthetic-gate h3{font-size:36px}.gate-fixtures{display:flex;flex-direction:column;gap:17px;margin-top:26px;font-size:24px;color:#B6DAC0}.gate-fixtures>span{display:flex;gap:12px;align-items:center}.experimental-gate{flex:1;padding-top:0}.experimental-gate h3{font-size:43px;margin-top:30px;margin-bottom:24px}.gate-chart{position:relative;height:155px;margin-top:41px}.gate-axis{position:absolute;left:0;right:10px;top:59px;height:2px;background:#52637D}.gate-limit{position:absolute;top:14px;left:68px;border-left:3px solid #9AE8B0;height:99px;padding-left:11px;z-index:2}.gate-limit b{font:23px monospace;color:#9AE8B0}.gate-limit span{position:absolute;top:105px;left:-67px;white-space:nowrap;font-size:19px;color:#A2B5CF}.observed-range{position:absolute;left:235px;right:26px;top:40px;height:40px;border-radius:20px;background:#EA433530;border:1px solid #EE8177;z-index:2}.observed-range b{position:absolute;top:-39px;left:40px;font:26px monospace;color:#FFB5AD}.observed-range span{position:absolute;top:51px;left:40px;font-size:20px;color:#D7BDBB}.test-equation{font-family:Georgia,serif;font-style:italic;font-size:43px;display:flex;gap:24px;align-items:center}.test-equation b{font-family:Arial;font-style:normal;font-size:64px;color:#FBBC04;font-weight:400}
.bottleneck-stage{display:flex;gap:70px;flex:1;align-items:center}.benchmark-chart{flex:1}.benchmark-chart>.eyebrow{font-size:19px;letter-spacing:1.8px;margin-bottom:49px}.bench-row{display:flex;align-items:center;gap:24px;margin-bottom:35px;font-size:27px}.bench-row>span{width:206px;flex-shrink:0}.bar-wrap{height:54px;flex:1;background:#1C2A3F;border-radius:5px;overflow:hidden}.bench-bar{height:100%;transform-origin:left;background:#9EAEC6;border-radius:5px}.cpu-bar{width:86%}.cuda-bar{width:90%;background:#A8C7FA}.bench-row>b{width:121px;font:28px monospace;white-space:nowrap}.bottleneck-insight{font-size:33px;color:#BECADF;line-height:1.4;margin-top:48px}.bottleneck-insight strong{color:var(--fg);font-weight:600}.ratio{width:500px;flex-shrink:0;text-align:center}.ratio>div:first-child{font-size:145px;line-height:1;font-weight:800;letter-spacing:-10px;color:#FFD36E}.ratio>div:first-child>span{font-size:95px}.ratio>p{font-size:25px;color:#C5D1E5;margin-top:23px}.inline-note{font-size:30px;display:inline-block;text-align:left;margin-top:61px;transform:rotate(4deg)}
.new-result{display:flex;align-items:center;gap:45px;flex:1}.new-stat{width:806px;flex-shrink:0}.new-stat .eyebrow{font-size:19px}.large-speed{font-size:210px;letter-spacing:-13px;line-height:1.1;font-weight:800;margin-top:22px;color:var(--blue)}.large-speed span{font-size:136px;letter-spacing:-8px}.new-stat>p{font:40px monospace;display:flex;gap:28px;align-items:center;margin-top:13px}.new-stat>p>span{color:#A1AEC2}.new-stat>p>b{font:50px Arial;color:#7084A6}.new-stat>p>strong{font-weight:500;color:var(--fg)}.streaming-diagram{position:relative;display:flex;align-items:center;gap:27px;width:800px;height:315px;margin-top:-65px}.stream-frames{position:relative;width:148px;height:160px;flex-shrink:0}.stream-frame{position:absolute;left:0;top:0;width:115px;height:115px;border:1px solid #7393BD;background:#192B43;border-radius:7px;font:28px monospace;color:#A8C7FA;display:flex;align-items:center;justify-content:center}.stf0{left:0;top:0}.stf1{left:7px;top:9px}.stf2{left:14px;top:18px}.stf3{left:21px;top:27px}.stf4{left:28px;top:36px}.stream-arrow{font-size:40px;color:#7A93B6}.stream-gpu{display:flex;flex-direction:column;align-items:center;position:relative;color:var(--blue)}.stream-gpu>span{position:absolute;top:178px;text-align:center;font-size:21px;color:#C2CDE0;white-space:nowrap}.stream-sum{width:150px;height:160px;display:flex;flex-direction:column;align-items:center;justify-content:center;font:95px Georgia;color:var(--fg)}.stream-sum span{font:17px Arial;letter-spacing:3px;margin-top:12px;color:var(--muted)}.stream-label{position:absolute;left:0;top:0;font-size:19px;letter-spacing:2px;color:#9AB1D0;white-space:nowrap}.stat-disclaimer{position:absolute;left:96px;top:781px;width:1600px;font-size:28px;line-height:1.35;color:#FFE094}.asterisk-note{position:absolute;right:180px;top:636px;font-size:29px;transform:rotate(4deg)}
.milestones{display:flex;flex-direction:column;gap:0;margin-top:25px}.milestone{display:flex;align-items:center;gap:34px;min-height:143px;border-bottom:1px solid #344761}.milestone>b{font-size:54px;letter-spacing:-2px;width:224px;flex-shrink:0}.milestone>div{flex:1}.milestone h3{font-size:31px;letter-spacing:-.8px}.milestone p{font-size:22px;color:#BCC9DC;margin-top:10px}.milestone .pill{font-size:18px;padding:12px 18px;min-width:192px}.shared-contract{font-size:36px;letter-spacing:-.8px;margin-top:10px}
.lessons{display:flex;flex-direction:column;gap:33px;margin-top:53px}.lesson{display:flex;align-items:center;gap:70px}.lesson>b{font-size:87px;letter-spacing:-4px;width:570px;flex-shrink:0;line-height:1.1;color:var(--blue)}.lesson>p{font-size:33px;max-width:820px;letter-spacing:-.5px}.snack{position:absolute;right:150px;top:745px;display:flex;align-items:center;gap:18px;color:#FFD77F}.snack svg{width:57px;height:57px}.snack span{font:24px/1.15 Georgia;font-style:italic}
.meta-layout{display:flex;align-items:center;gap:63px;flex:1}.meta-copy{width:885px;flex-shrink:0}.meta-title{font-size:106px;line-height:1.0;letter-spacing:-5px;margin-top:26px}.chat{display:flex;align-items:center;gap:18px;margin-top:19px}.chat>span{font:16px monospace;border:1px solid #456286;border-radius:5px;padding:7px 10px;color:#ACC8EE;width:86px;text-align:center}.chat p{font-size:27px;color:#C3D1E4}.joke1{margin-top:35px}.joke2 p{color:var(--fg)}.video-task{width:776px;border:1px solid #526B91;border-radius:15px;padding:24px;background:#182439}.video-task-head{display:flex;justify-content:space-between;font:19px monospace;letter-spacing:1px;margin-bottom:20px;color:#AEC4E2}.video-task-head>span{color:#FFD36E}.mini-film{height:280px;border:1px solid #51698D;border-radius:8px;position:relative;display:flex;flex-direction:column;justify-content:center;padding:37px;background:radial-gradient(ellipse at 90% 5%,#274369,#101723 75%)}.mini-kicker{font-size:12px;letter-spacing:2px;color:#AEC1DB;margin-bottom:14px}.mini-film>b{font-size:57px;line-height:1.0;letter-spacing:-3px}.mini-film>b>span{color:var(--blue)}.mini-play{position:absolute;right:42px;top:118px;color:#A8C7FA;font-size:42px}.edit-tracks{position:relative;display:flex;flex-direction:column;gap:10px;margin-top:22px}.edit-track{height:26px;display:flex;gap:7px;align-items:center}.edit-track>b{font:12px monospace;width:78px;letter-spacing:1px;color:#A5BDDD}.edit-track>i{height:20px;background:#3E6495;border-radius:3px;flex:1}.edit-track:nth-child(2)>i{background:#557C67}.edit-track:nth-child(3)>i{background:#9A8146}.playhead{position:absolute;left:91px;width:2px;top:-6px;bottom:-7px;background:var(--fg)}.playhead:before{content:'';position:absolute;left:-5px;top:-3px;width:12px;height:8px;background:var(--fg)}.video-deliverable{font-size:23px;color:#CED8E7;margin-top:27px;line-height:1.3}
.endcard{display:flex;flex-direction:column;align-items:center;justify-content:center;flex:1;text-align:center;margin-top:-15px}.end-mark{color:var(--blue);margin-bottom:17px}.end-title{font-size:141px;line-height:.95;letter-spacing:-8px;font-weight:800}.end-tag{font-size:32px;letter-spacing:9px;color:#FFE094;margin-top:30px}.end-partners{font-size:35px;margin-top:39px;letter-spacing:.5px}.end-partners b{font-weight:400;color:#657B9C;margin:0 24px}.end-tools{font-size:18px;letter-spacing:2.0px;color:#A7B8CF;margin-top:29px}
'''

out=['<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=1920"><title>Motion, corrected.</title><style>',css,'</style></head><body><div id="film" data-composition-id="motioncorr-film" data-start="0" data-duration="180" data-width="1920" data-height="1080">']
for i,(scene,body) in enumerate(zip(story['scenes'],sc)):
 start=max(0,scene['start']-.34);end=min(180,scene['end']+.35)
 bg='<div class="scene-bg" data-layout-ignore><div class="grid-lines"></div><div class="orbital"></div>'+''.join(f'<b class="bg-plus" style="left:{115+(k*331)%1720}px;top:{100+(k*257)%760}px">+</b>' for k in range(11))+'<div class="noise-line"></div></div>'
 out.append(f'<section id="{scene["id"]}" class="scene clip" data-start="{start}" data-duration="{end-start}" data-track-index="{i%2}" style="z-index:{i+1}"><div class="scene-inner">{bg}<div class="scene-content">{body}</div></div></section>')
out.append('<div class="header"><div class="brand"><span class="brandmark"><i></i><i></i><i></i></span>MOTIONCORR / LAB NOTES</div><div class="event">STFC × GOOGLE × PA <span class="g-dots"><i></i><i></i><i></i><i></i></span></div></div>')
out.append('<div class="chapterline">'+''.join(f'<span class="chapter" id="ch{i}">{s["chapter"]}<b>{i+1:02d} / {len(sc):02d}</b></span>' for i,s in enumerate(story['scenes']))+'</div>')
cues=[c for scene in story['scenes'] for c in scene['cues']]
out.append('<div class="caption-box">'+''.join(f'<div class="caption clip" id="cap{i}" data-start="{a}" data-duration="{b-a}" data-track-index="10"><span>{esc(t)}</span></div>' for i,(a,b,t) in enumerate(cues))+'</div>')
out.append('<audio id="score" src="assets/original-score.m4a" data-start="0" data-duration="180" data-track-index="20" data-volume="1" preload="auto"></audio><div class="progress-track"><div class="progress-bar"></div></div></div><script src="assets/gsap.min.js"></script><script>')
js=r'''
window.__timelines=window.__timelines||{};
const tl=gsap.timeline({paused:true});
const scenes=STORY.scenes;
for(let i=0;i<scenes.length;i++){
 const s=scenes[i],base=s.start,sel='#'+s.id;
 tl.from(sel+' .scene-inner',{opacity:0,duration:.68,ease:'power1.inOut',immediateRender:true},Math.max(0,base-.34));
 const els=document.querySelectorAll(sel+' .reveal');
 els.forEach((el,k)=>tl.from(el,{y:30,opacity:0,duration:.72,ease:'power3.out',immediateRender:true},base+.3+Math.min(k*.11,.88)));
 tl.from(sel+' .grid-lines',{x:-14,y:-7,duration:s.end-s.start+.68,ease:'none',immediateRender:true},Math.max(0,base-.34));
 tl.from(sel+' .orbital',{rotation:-8,x:30,duration:s.end-s.start+.68,ease:'none',immediateRender:true},Math.max(0,base-.34));
}
tl.set('.chapter',{opacity:0},0);
scenes.forEach((s,i)=>{tl.set('#ch'+i,{opacity:1},s.start);tl.set('#ch'+i,{opacity:0},s.end);});
tl.set('.caption',{opacity:0},0);
let capnum=0;scenes.forEach(s=>s.cues.forEach(c=>{let id='#cap'+capnum++;tl.set(id,{opacity:1},c[0]);tl.set(id,{opacity:0},c[1]);}));
tl.from('.header',{opacity:0,y:-10,duration:.7,ease:'power2.out'},.08);
tl.from('.progress-bar',{scaleX:0,duration:180,ease:'none'},0);
// The opening wandering frames converge to the same detector coordinates.
for(let i=0;i<4;i++){
 tl.from('#s00 .sf'+i,{x:55+i*18,y:30-i*23,rotation:4-i*3,duration:1.4,ease:'power3.out'},.8+i*.14);
 tl.to('#s00 .sf'+i,{x:-i*22,y:i*22,duration:2.0,ease:'power2.inOut'},6.0+i*.07);
}
tl.to('#s00 .stack-space',{rotation:0,duration:2.4,ease:'power2.inOut'},6);
// Detector comparison stays alive while subtitles explain the problem.
tl.from('#s01 .unaligned img',{scale:1.075,x:-12,duration:11.3,ease:'none'},10.7);
tl.from('#s01 .aligned img',{scale:1.075,x:8,duration:11.3,ease:'none'},10.7);
for(let i=0;i<4;i++)tl.from('#step'+i,{scale:.93,duration:.55,ease:'back.out(1.25)'},23+i*2.3);
tl.from('#s02 .spectrum i',{scaleY:.15,stagger:.06,duration:.7,ease:'power2.out'},27.5);
tl.to('#s02 .flowline i',{x:1330,duration:8.5,ease:'none'},24.1);
tl.to('#s02 .moving-frame img',{x:-9,y:6,duration:1.2,ease:'sine.inOut',repeat:3,yoyo:true},23.3);
for(let i=0;i<4;i++){tl.from('#task'+i+' .taskcheck',{scale:0,opacity:0,duration:.36,ease:'back.out(2)'},48.6+i*2.0);tl.from('#task'+i,{x:18,duration:.55,ease:'power3.out'},48.4+i*2.0);}
// Personified labels are illustrative dialogue, not quoted tool output.
for(let i=0;i<5;i++)tl.from('#s05 .r'+i+' .agent-symbol',{scale:.8,duration:.5,ease:'back.out(2)'},61.1+i*.3);
for(let i=0;i<5;i++)tl.from('#fn'+i+' .flow-icon',{scale:.84,duration:.55,ease:'back.out(1.5)'},76.1+i*1.05);
for(let i=0;i<24;i++)tl.from('#movie'+i,{opacity:0,scale:.7,duration:.35,ease:'back.out(1.4)'},90.0+i*.15);
tl.from('#s08 .observed-range',{scaleX:0,transformOrigin:'left center',duration:1.25,ease:'power2.out'},105.2);
tl.from('#s08 .gate-limit',{opacity:0,duration:.5},103.0);
tl.from('#s09 .cpu-bar',{scaleX:0,duration:1.5,ease:'power2.out'},114.1);
tl.from('#s09 .cuda-bar',{scaleX:0,duration:1.5,ease:'power2.out'},115.0);
for(let i=0;i<5;i++)tl.to('#s10 .stf'+i,{x:36,duration:1.25,yoyo:true,repeat:5,ease:'sine.inOut'},125.7+i*.17);
for(let i=0;i<3;i++)tl.from('#s12 .lesson'+i,{opacity:0,x:-35,duration:.75,ease:'power3.out'},150+i*3.5);
tl.from('#s13 .joke1',{opacity:0,x:-22,duration:.6,ease:'power3.out'},168.0);
tl.from('#s13 .joke2',{opacity:0,x:-22,duration:.6,ease:'power3.out'},170.2);
tl.to('#s13 .playhead',{x:552,duration:10.5,ease:'none'},164);
tl.to('#s13 .mini-play',{scale:1.13,duration:.8,yoyo:true,repeat:7,ease:'sine.inOut'},164.2);
window.__timelines['motioncorr-film']=tl;
window.seekFilm=function(t){tl.totalTime(Math.max(0,Math.min(179.999,t)),false);};
window.seekFilm(0);
'''.replace('STORY',json.dumps(story))
out.extend([js,'</script></body></html>'])
(R/'index.html').write_text(''.join(out))
# Sidecar captions and readable narration.
def stamp(t,sep=','):
 ms=round(t*1000);h,ms=divmod(ms,3600000);m,ms=divmod(ms,60000);s,ms=divmod(ms,1000);return f'{h:02d}:{m:02d}:{s:02d}{sep}{ms:03d}'
srt=[];vtt=['WEBVTT\n'];script=['# Motion, corrected.\n\nThree-minute narration, 379 words. No voiceover has been generated.\n']
for i,(a,b,t) in enumerate(cues):
 lines='\n'.join(textwrap.wrap(t,width=71,break_long_words=False,break_on_hyphens=False))
 srt.append(f'{i+1}\n{stamp(a)} --> {stamp(b)}\n{lines}\n')
 vtt.append(f'{stamp(a,".")} --> {stamp(b,".")}\n{lines}\n')
for s in story['scenes']:
 script.append(f'\n## {stamp(s["start"],".")[:8]}–{stamp(s["end"],".")[:8]} · {s["title"]}\n\n'+' '.join(c[2] for c in s['cues'])+'\n')
(R/'subtitles.srt').write_text('\n'.join(srt));(R/'subtitles.vtt').write_text('\n'.join(vtt));(R/'narration.md').write_text(''.join(script))
print('Built',R/'index.html', 'size', (R/'index.html').stat().st_size)
