#!/usr/bin/env python3
"""Extract the production dose-weighting device code verbatim into a header.

The graph probe must run the *same* kernels as `cudaDoseWeightAndInterpolateDevice`,
otherwise an exactness result would only compare the probe against itself. Copying
the text by hand would drift silently, so the regions are lifted from the production
translation unit at build time and the build fails if any of them is missing.
"""
import hashlib
import re
import sys
from pathlib import Path

SRC = Path(sys.argv[1])
OUT = Path(sys.argv[2])

text = SRC.read_text()

REGIONS = [
    ("struct FramePolynomial", r"^struct FramePolynomial \{\n(?:.*\n)*?^\};\n"),
    ("polynomialForFrame", r"^FramePolynomial polynomialForFrame\(.*\n(?:.*\n)*?^\}\n"),
    ("applyDoseWeightKernel", r"^__global__ void applyDoseWeightKernel\(\n(?:.*\n)*?^\}\n"),
    ("interpolateAndAccumulatePolynomialKernel",
     r"^__global__ void interpolateAndAccumulatePolynomialKernel\(\n(?:.*\n)*?^\}\n"),
    ("accumulateDirectKernel", r"^__global__ void accumulateDirectKernel\(\n(?:.*\n)*?^\}\n"),
]

parts = []
digest = hashlib.sha256()
for name, pattern in REGIONS:
    m = re.search(pattern, text, re.MULTILINE)
    if not m:
        sys.exit(f"extract_kernels.py: region '{name}' not found in {SRC}")
    body = m.group(0)
    digest.update(body.encode())
    parts.append(f"// ---- verbatim from {SRC.name}: {name} ----\n{body}")

OUT.write_text(
    "// GENERATED by tools/cuda_graph_dw/extract_kernels.py -- do not edit.\n"
    f"// source: {SRC}\n"
    f"// extracted-region sha256: {digest.hexdigest()}\n"
    "#pragma once\n"
    "#include <cmath>\n"
    "struct ProbeModel { double cx[18]; double cy[18];\n"
    "    double coeffX(int i) const { return cx[i]; }\n"
    "    double coeffY(int i) const { return cy[i]; }\n"
    "};\n"
    "typedef ProbeModel ThirdOrderPolynomialModel;\n"
    "namespace {\n" + "\n".join(parts) + "\n} // namespace\n"
)
print(f"extracted {len(REGIONS)} regions, sha256={digest.hexdigest()}")
