#!/usr/bin/env python3
"""
Standalone Sub-Stage Timing Breakdown Plotter
Decoupled plotting script generated by MotionCorr Visualization Agent.
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple


def parse_benchmark_json(json_path: Path) -> List[Dict]:
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data.get("cases", [])


def extract_stage_matrix(cases: List[Dict]) -> Tuple[List[str], List[str], List[List[float]]]:
    sorted_cases = sorted(cases, key=lambda c: c.get("threads", 1))
    categories = [f"{c.get('threads', 1)} Thread(s)" for c in sorted_cases]
    
    # Collect all unique stage names preserving order
    all_stages = []
    for c in sorted_cases:
        for st in c.get("stage_breakdowns", []):
            tag = st.get("tag", "")
            if tag and tag not in all_stages:
                all_stages.append(tag)
                
    if not all_stages:
        all_stages = ["Total Alignment", "Dose Weighting", "I/O Overhead"]

    matrix = []
    for c in sorted_cases:
        stage_map = {st.get("tag", ""): st.get("mean_sec", 0.0) for st in c.get("stage_breakdowns", [])}
        row = [stage_map.get(name, 0.0) for name in all_stages]
        matrix.append(row)

    return categories, all_stages, matrix


def plot_with_matplotlib(
    title: str,
    categories: List[str],
    stage_names: List[str],
    stage_matrix: List[List[float]],
    out_png: Path
) -> bool:
    try:
        import matplotlib.pyplot as plt
        import matplotlib
        import numpy as np
        matplotlib.use("Agg")
    except ImportError:
        return False

    fig, ax = plt.subplots(figsize=(10, 5), dpi=150)
    y_pos = np.arange(len(categories))
    
    colors = ["#2563eb", "#38bdf8", "#10b981", "#f59e0b", "#8b5cf6", "#ec4899", "#64748b"]
    lefts = np.zeros(len(categories))
    
    for s_idx, s_name in enumerate(stage_names):
        vals = [row[s_idx] for row in stage_matrix]
        c = colors[s_idx % len(colors)]
        ax.barh(y_pos, vals, left=lefts, height=0.55, label=s_name, color=c, edgecolor="white")
        lefts += np.array(vals)

    ax.set_yticks(y_pos)
    ax.set_yticklabels(categories, fontsize=10, fontweight="bold")
    ax.set_xlabel("Cumulative Execution Time (seconds)", fontsize=11, fontweight="bold")
    ax.set_title(title, fontsize=13, fontweight="bold", pad=15)
    ax.legend(loc="upper right", framealpha=0.9)
    ax.grid(True, axis="x", linestyle="--", alpha=0.5)

    plt.tight_layout()
    out_png.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(out_png, bbox_inches="tight")
    plt.close()
    return True


def plot_with_svg(
    title: str,
    categories: List[str],
    stage_names: List[str],
    stage_matrix: List[List[float]],
    out_svg: Path
) -> None:
    width, height = 850, 450
    margin_l, margin_r, margin_t, margin_b = 130, 40, 60, 90
    plot_w = width - margin_l - margin_r
    plot_h = height - margin_t - margin_b

    colors = ["#2563eb", "#38bdf8", "#10b981", "#f59e0b", "#8b5cf6", "#ec4899", "#64748b"]
    totals = [sum(row) for row in stage_matrix]
    max_tot = max(totals) * 1.1 if totals else 100.0

    lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" width="{width}" height="{height}">',
        f'  <rect width="{width}" height="{height}" fill="#ffffff" rx="8"/>',
        f'  <text x="{width / 2}" y="32" font-family="sans-serif" font-size="16" font-weight="bold" fill="#0f172a" text-anchor="middle">{title}</text>',
        f'  <rect x="{margin_l}" y="{margin_t}" width="{plot_w}" height="{plot_h}" fill="#f8fafc" stroke="#e2e8f0"/>',
    ]

    for i in range(6):
        val = (max_tot / 5) * i
        x = margin_l + (val / max_tot) * plot_w
        lines.append(f'  <line x1="{x:.1f}" y1="{margin_t}" x2="{x:.1f}" y2="{margin_t + plot_h}" stroke="#e2e8f0"/>')
        lines.append(f'  <text x="{x:.1f}" y="{margin_t + plot_h + 18}" font-family="sans-serif" font-size="10" fill="#64748b" text-anchor="middle">{val:.1f}s</text>')

    n_cats = len(categories)
    bar_h = min(40.0, (plot_h / (n_cats or 1)) * 0.6)
    gap = (plot_h - n_cats * bar_h) / (n_cats + 1)

    for c_idx, cat in enumerate(categories):
        y = margin_t + gap * (c_idx + 1) + bar_h * c_idx
        lines.append(f'  <text x="{margin_l - 10}" y="{y + bar_h / 2 + 4:.1f}" font-family="sans-serif" font-size="11" font-weight="bold" fill="#334155" text-anchor="end">{cat}</text>')
        curr_x = margin_l
        for s_idx, s_val in enumerate(stage_matrix[c_idx]):
            if s_val <= 0:
                continue
            seg_w = (s_val / max_tot) * plot_w
            c = colors[s_idx % len(colors)]
            lines.append(f'  <rect x="{curr_x:.1f}" y="{y:.1f}" width="{seg_w:.1f}" height="{bar_h:.1f}" fill="{c}" stroke="#ffffff" stroke-width="0.5"/>')
            if seg_w > 40:
                lines.append(f'  <text x="{curr_x + seg_w / 2:.1f}" y="{y + bar_h / 2 + 4:.1f}" font-family="sans-serif" font-size="9" font-weight="bold" fill="#ffffff" text-anchor="middle">{s_val:.1f}s</text>')
            curr_x += seg_w

    leg_x = margin_l
    leg_y = height - 35
    for s_idx, name in enumerate(stage_names):
        c = colors[s_idx % len(colors)]
        lines.append(f'  <rect x="{leg_x}" y="{leg_y}" width="14" height="14" fill="{c}" rx="2"/>')
        lines.append(f'  <text x="{leg_x + 18}" y="{leg_y + 11}" font-family="sans-serif" font-size="10" fill="#334155">{name}</text>')
        leg_x += len(name) * 7 + 45

    lines.append(f'  <text x="{margin_l + plot_w / 2}" y="{margin_t + plot_h + 35}" font-family="sans-serif" font-size="11" font-weight="bold" fill="#334155" text-anchor="middle">Cumulative Stage Time (seconds)</text>')
    lines.append('</svg>')

    out_svg.parent.mkdir(parents=True, exist_ok=True)
    with open(out_svg, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main():
    parser = argparse.ArgumentParser(description="Standalone Sub-Stage Timing Breakdown Plotter")
    parser.add_argument("--input", required=True, type=Path, help="Path to benchmark JSON summary")
    parser.add_argument("--out-dir", type=Path, default=Path("plots"), help="Output directory for plots")
    parser.add_argument("--title", type=str, default="MotionCorr Telemetry (Stages)", help="Plot title")
    parser.add_argument("--format", nargs="+", default=["svg", "png"], choices=["svg", "png", "all"], help="Output formats")
    args = parser.parse_args()

    if not args.input.exists():
        print(f"Error: input file {args.input} does not exist.", file=sys.stderr)
        sys.exit(1)

    cases = parse_benchmark_json(args.input)
    if not cases:
        print(f"Error: no benchmark cases found in {args.input}", file=sys.stderr)
        sys.exit(1)

    categories, stage_names, stage_matrix = extract_stage_matrix(cases)
    print(f"[Stage Breakdown] Processed {len(categories)} categories across {len(stage_names)} stages")

    args.out_dir.mkdir(parents=True, exist_ok=True)
    stem = args.input.stem

    if "svg" in args.format or "all" in args.format:
        svg_path = args.out_dir / f"{stem}_stages.svg"
        plot_with_svg(args.title, categories, stage_names, stage_matrix, svg_path)
        print(f"[Stage Breakdown] Generated SVG: {svg_path}")

    if "png" in args.format or "all" in args.format:
        png_path = args.out_dir / f"{stem}_stages.png"
        if plot_with_matplotlib(args.title, categories, stage_names, stage_matrix, png_path):
            print(f"[Stage Breakdown] Generated PNG: {png_path}")
        else:
            print("[Stage Breakdown] Matplotlib unavailable; SVG was generated as primary artifact.")


if __name__ == "__main__":
    main()
