#!/usr/bin/env python3
"""
General-Purpose Visualization Agent Orchestrator (`agents/visualization_agent/scripts/visualize.py`)

Autonomously discovers result telemetry, synthesizes standalone decoupled plotting scripts
under `tools/plots/`, executes them, and compiles markdown visualization reports.
Saves all plots into a dedicated plot folder with a timestamped sub-directory as both SVG and PNG.
"""

import argparse
import datetime
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple


def get_agent_root() -> Path:
    return Path(__file__).resolve().parent.parent


def get_repo_root() -> Path:
    return get_agent_root().parent.parent


def detect_data_type(data_path: Path) -> str:
    suffix = data_path.suffix.lower()
    if suffix == ".star":
        return "trajectory"
    if suffix == ".json":
        try:
            with open(data_path, "r", encoding="utf-8") as f:
                d = json.load(f)
            if "cases" in d:
                cases = d.get("cases", [])
                threads = {c.get("threads") for c in cases}
                if len(threads) > 1:
                    return "scaling"
                return "stages"
        except Exception:
            pass
    return "scaling"


def scaffold_standalone_script(
    plot_type: str,
    out_script: Path,
    custom_title: Optional[str] = None
) -> Path:
    """Instantiate a standalone plotting script from agent templates."""
    agent_root = get_agent_root()
    templates_dir = agent_root / "templates"
    
    template_map = {
        "scaling": templates_dir / "speedup_scaling_template.py.jinja",
        "stages": templates_dir / "stage_breakdown_template.py.jinja",
        "trajectory": templates_dir / "trajectory_vector_template.py.jinja",
        "comparative": templates_dir / "comparative_delta_template.py.jinja",
    }
    
    tpl_path = template_map.get(plot_type)
    if not tpl_path or not tpl_path.exists():
        raise FileNotFoundError(f"Template for plot type '{plot_type}' not found at {tpl_path}")
        
    with open(tpl_path, "r", encoding="utf-8") as f:
        content = f.read()
        
    if custom_title:
        content = content.replace("MotionCorr Multi-Thread CPU Scaling", custom_title)
        content = content.replace("MotionCorr Sub-Stage Timing Breakdown", custom_title)
        content = content.replace("MotionCorr 2D Motion Trajectory", custom_title)
        content = content.replace("MotionCorr Optimization Delta Comparison", custom_title)
        
    out_script.parent.mkdir(parents=True, exist_ok=True)
    with open(out_script, "w", encoding="utf-8") as f:
        f.write(content)
        
    # Make script executable
    out_script.chmod(0o755)
    print(f"[Visualization Agent] Scaffolding standalone tool -> {out_script}")
    return out_script


def execute_standalone_script(
    script_path: Path,
    args: List[str]
) -> Tuple[int, str, str]:
    """Execute the standalone script in a separate Python process to ensure total decoupling."""
    cmd = [sys.executable, str(script_path.resolve())] + args
    res = subprocess.run(cmd, capture_output=True, text=True, encoding="utf-8", errors="replace")
    return res.returncode, res.stdout, res.stderr


def build_markdown_report(
    title: str,
    source_data: str,
    plot_paths: List[Path],
    out_report: Path,
    extra_summary: str = ""
) -> None:
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        f"# Visualization Report: {title}",
        "",
        f"- **Generated By**: MotionCorr Visualization Agent (`agents/visualization_agent/`)",
        f"- **Timestamp**: `{timestamp}`",
        f"- **Source Dataset**: `{source_data}`",
        f"- **Output Formats**: SVG & PNG",
        "",
        "---",
        "",
        "## Generated Visual Plots",
        ""
    ]
    
    svg_plots = [p for p in plot_paths if p.suffix.lower() == ".svg"]
    png_plots = [p for p in plot_paths if p.suffix.lower() == ".png"]
    
    # Pair by stem if possible
    seen_stems = set()
    for p in plot_paths:
        if p.stem in seen_stems:
            continue
        seen_stems.add(p.stem)
        svg_match = next((s for s in svg_plots if s.stem == p.stem), None)
        png_match = next((s for s in png_plots if s.stem == p.stem), None)
        
        lines.append(f"### {p.stem}")
        if svg_match:
            lines.append(f"- **Vector SVG**: `[{svg_match.name}]({svg_match.name})`")
        if png_match:
            lines.append(f"- **Raster PNG**: `[{png_match.name}]({png_match.name})`")
        lines.append("")
        # Embed SVG or PNG in markdown
        display_img = png_match.name if png_match else (svg_match.name if svg_match else p.name)
        lines.append(f"![{p.stem}]({display_img})")
        lines.append("")
        
    if extra_summary:
        lines.extend([
            "---",
            "",
            "## Summary & Observations",
            "",
            extra_summary
        ])
        
    out_report.parent.mkdir(parents=True, exist_ok=True)
    with open(out_report, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"[Visualization Agent] Generated Markdown Report -> {out_report}")


def resolve_output_directory(base_out_dir: Path, use_timestamp_subdir: bool = True) -> Path:
    """Resolve destination directory, creating a timestamped sub-directory if enabled."""
    if use_timestamp_subdir:
        timestamp_str = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        target_dir = base_out_dir / timestamp_str
    else:
        target_dir = base_out_dir
    target_dir.mkdir(parents=True, exist_ok=True)
    return target_dir


def main():
    parser = argparse.ArgumentParser(
        description="MotionCorr General-Purpose Visualization Agent Orchestrator"
    )
    parser.add_argument("--data", type=Path, help="Path to input data (JSON summary, STAR trajectory)")
    parser.add_argument("--type", choices=["auto", "scaling", "stages", "trajectory", "comparative"], default="auto", help="Chart category")
    parser.add_argument("--baseline", type=Path, help="Path to baseline JSON (for comparative mode)")
    parser.add_argument("--candidate", type=Path, help="Path to candidate JSON (for comparative mode)")
    parser.add_argument("--out-script", type=Path, help="Destination path for generated standalone script in tools/plots/")
    parser.add_argument("--generate", action="store_true", help="Scaffold standalone plotting script")
    parser.add_argument("--render", action="store_true", help="Execute generated script to produce plots")
    parser.add_argument("--out-dir", type=Path, default=Path("plots"), help="Base directory for generated plots (default: plots/)")
    parser.add_argument("--no-timestamp", action="store_true", help="Do not create a timestamped sub-directory; write directly to --out-dir")
    parser.add_argument("--report", type=Path, help="Path to markdown summary report (defaults to report.md in output directory)")
    parser.add_argument("--title", type=str, help="Custom chart/report title")
    parser.add_argument("--format", nargs="+", default=["svg", "png"], choices=["svg", "png", "all"], help="Plot output formats (default: svg png)")
    
    args = parser.parse_args()
    repo_root = get_repo_root()
    
    # Determine plot type
    if args.baseline and args.candidate:
        plot_type = "comparative"
        source_desc = f"{args.baseline.name} vs {args.candidate.name}"
    elif args.data:
        plot_type = detect_data_type(args.data) if args.type == "auto" else args.type
        source_desc = str(args.data)
    else:
        # Default inspection of latest review benchmark data if present
        latest_json = repo_root / "agents" / "reviews" / "issue_9_benchmark_data.json"
        if latest_json.exists():
            args.data = latest_json
            plot_type = "scaling"
            source_desc = str(latest_json)
        else:
            parser.print_help()
            sys.exit(1)
            
    title = args.title or f"MotionCorr Telemetry ({plot_type.capitalize()})"
    
    # 1. Determine destination script in tools/plots/
    if not args.out_script:
        stem = args.data.stem if args.data else "comparison"
        args.out_script = repo_root / "tools" / "plots" / f"plot_{stem}_{plot_type}.py"
        
    # 2. Scaffold standalone script
    scaffold_standalone_script(plot_type, args.out_script, title)
    
    # 3. Render plots if requested or by default
    generated_plots = []
    if args.render or not args.generate:
        target_dir = resolve_output_directory(args.out_dir, use_timestamp_subdir=not args.no_timestamp)
        print(f"[Visualization Agent] Output Directory: {target_dir}")
        
        formats = ["svg", "png"] if ("all" in args.format or ("svg" in args.format and "png" in args.format)) else args.format
        
        cmd_args = []
        if plot_type == "comparative":
            cmd_args.extend(["--baseline", str(args.baseline.resolve()), "--candidate", str(args.candidate.resolve()), "--out-dir", str(target_dir.resolve()), "--title", title, "--format"] + formats)
        else:
            cmd_args.extend(["--input", str(args.data.resolve()), "--out-dir", str(target_dir.resolve()), "--title", title, "--format"] + formats)
            
        code, stdout, stderr = execute_standalone_script(args.out_script, cmd_args)
        if code != 0:
            print(f"[Visualization Agent] Error executing generated script:\n{stderr}", file=sys.stderr)
            sys.exit(code)
            
        print(stdout)
        # Find created plots in target_dir
        for p in target_dir.glob("*.*"):
            if p.suffix.lower() in [".svg", ".png"]:
                generated_plots.append(p)
                
        # 4. Generate report in target_dir
        report_path = args.report or (target_dir / "report.md")
        build_markdown_report(title, source_desc, generated_plots, report_path)
            
    print(f"\n[Visualization Agent] SUCCESS: Scaffolded and verified {args.out_script.name}")
    if generated_plots:
        print("[Visualization Agent] Generated Plot Artifacts:")
        for p in sorted(generated_plots):
            print(f"  - {p}")


if __name__ == "__main__":
    main()
