#!/usr/bin/env python3
"""
General-Purpose Visualization Agent Orchestrator (`agents/visualization_agent/scripts/visualize.py`)

Autonomously discovers result telemetry, synthesizes standalone decoupled plotting scripts
under `tools/plots/`, executes them, and compiles markdown visualization reports.
"""

import argparse
import datetime
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple


def get_agent_root() -> Path:
    return Path(__file__).resolve().parent.parent


def get_repo_root() -> Path:
    return get_agent_root().parent.parent


def detect_data_type(data_path: Path) -> str:
    suffix = data_path.suffix.lower()
    if suffix == ".star":
        return "trajectory"
    if suffix == ".json":
        try:
            with open(data_path, "r", encoding="utf-8") as f:
                d = json.load(f)
            if "cases" in d:
                # Check if multiple cases with different threads
                cases = d.get("cases", [])
                threads = {c.get("threads") for c in cases}
                if len(threads) > 1:
                    return "scaling"
                return "stages"
        except Exception:
            pass
    return "scaling"


def scaffold_standalone_script(
    plot_type: str,
    out_script: Path,
    custom_title: Optional[str] = None
) -> Path:
    """Instantiate a standalone plotting script from agent templates."""
    agent_root = get_agent_root()
    templates_dir = agent_root / "templates"
    
    template_map = {
        "scaling": templates_dir / "speedup_scaling_template.py.jinja",
        "stages": templates_dir / "stage_breakdown_template.py.jinja",
        "trajectory": templates_dir / "trajectory_vector_template.py.jinja",
        "comparative": templates_dir / "comparative_delta_template.py.jinja",
    }
    
    tpl_path = template_map.get(plot_type)
    if not tpl_path or not tpl_path.exists():
        raise FileNotFoundError(f"Template for plot type '{plot_type}' not found at {tpl_path}")
        
    with open(tpl_path, "r", encoding="utf-8") as f:
        content = f.read()
        
    if custom_title:
        content = content.replace("MotionCorr Multi-Thread CPU Scaling", custom_title)
        content = content.replace("MotionCorr Sub-Stage Timing Breakdown", custom_title)
        content = content.replace("MotionCorr 2D Motion Trajectory", custom_title)
        content = content.replace("MotionCorr Optimization Delta Comparison", custom_title)
        
    out_script.parent.mkdir(parents=True, exist_ok=True)
    with open(out_script, "w", encoding="utf-8") as f:
        f.write(content)
        
    # Make script executable
    out_script.chmod(0o755)
    print(f"[Visualization Agent] Scaffolding standalone tool -> {out_script}")
    return out_script


def execute_standalone_script(
    script_path: Path,
    args: List[str]
) -> Tuple[int, str, str]:
    """Execute the standalone script in a separate Python process to ensure total decoupling."""
    cmd = [sys.executable, str(script_path.resolve())] + args
    res = subprocess.run(cmd, capture_output=True, text=True, encoding="utf-8", errors="replace")
    return res.returncode, res.stdout, res.stderr


def build_markdown_report(
    title: str,
    source_data: str,
    plot_paths: List[Path],
    out_report: Path,
    extra_summary: str = ""
) -> None:
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        f"# Visualization Report: {title}",
        "",
        f"- **Generated By**: MotionCorr Visualization Agent (`agents/visualization_agent/`)",
        f"- **Timestamp**: `{timestamp}`",
        f"- **Source Dataset**: `{source_data}`",
        "",
        "---",
        "",
        "## Generated Visual Plots",
        ""
    ]
    
    for p in plot_paths:
        lines.append(f"### {p.name}")
        rel_path = p.name  # Use relative path if in same directory
        lines.append(f"![{p.stem}]({rel_path})")
        lines.append("")
        
    if extra_summary:
        lines.extend([
            "---",
            "",
            "## Summary & Observations",
            "",
            extra_summary
        ])
        
    out_report.parent.mkdir(parents=True, exist_ok=True)
    with open(out_report, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"[Visualization Agent] Generated Markdown Report -> {out_report}")


def main():
    parser = argparse.ArgumentParser(
        description="MotionCorr General-Purpose Visualization Agent Orchestrator"
    )
    parser.add_argument("--data", type=Path, help="Path to input data (JSON summary, STAR trajectory)")
    parser.add_argument("--type", choices=["auto", "scaling", "stages", "trajectory", "comparative"], default="auto", help="Chart category")
    parser.add_argument("--baseline", type=Path, help="Path to baseline JSON (for comparative mode)")
    parser.add_argument("--candidate", type=Path, help="Path to candidate JSON (for comparative mode)")
    parser.add_argument("--out-script", type=Path, help="Destination path for generated standalone script in tools/plots/")
    parser.add_argument("--generate", action="store_true", help="Scaffold standalone plotting script")
    parser.add_argument("--render", action="store_true", help="Execute generated script to produce plots")
    parser.add_argument("--out-dir", type=Path, default=Path("agents/reviews/plots"), help="Directory for generated plot images")
    parser.add_argument("--report", type=Path, help="Path to markdown summary report")
    parser.add_argument("--title", type=str, help="Custom chart/report title")
    parser.add_argument("--format", nargs="+", default=["svg", "png"], choices=["svg", "png", "all"], help="Plot output formats")
    
    args = parser.parse_args()
    repo_root = get_repo_root()
    
    # Determine plot type
    if args.baseline and args.candidate:
        plot_type = "comparative"
        source_desc = f"{args.baseline.name} vs {args.candidate.name}"
    elif args.data:
        plot_type = detect_data_type(args.data) if args.type == "auto" else args.type
        source_desc = str(args.data)
    else:
        # Default inspection of latest review benchmark data if present
        latest_json = repo_root / "agents" / "reviews" / "issue_9_benchmark_data.json"
        if latest_json.exists():
            args.data = latest_json
            plot_type = "scaling"
            source_desc = str(latest_json)
        else:
            parser.print_help()
            sys.exit(1)
            
    title = args.title or f"MotionCorr Telemetry ({plot_type.capitalize()})"
    
    # 1. Determine destination script in tools/plots/
    if not args.out_script:
        stem = args.data.stem if args.data else "comparison"
        args.out_script = repo_root / "tools" / "plots" / f"plot_{stem}_{plot_type}.py"
        
    # 2. Scaffold standalone script
    scaffold_standalone_script(plot_type, args.out_script, title)
    
    # 3. Render plots if requested or by default
    generated_plots = []
    if args.render or not args.generate:
        args.out_dir.mkdir(parents=True, exist_ok=True)
        cmd_args = []
        if plot_type == "comparative":
            cmd_args.extend(["--baseline", str(args.baseline.resolve()), "--candidate", str(args.candidate.resolve()), "--out-dir", str(args.out_dir.resolve()), "--title", title])
        else:
            cmd_args.extend(["--input", str(args.data.resolve()), "--out-dir", str(args.out_dir.resolve()), "--title", title, "--format"] + args.format)
            
        code, stdout, stderr = execute_standalone_script(args.out_script, cmd_args)
        if code != 0:
            print(f"[Visualization Agent] Error executing generated script:\n{stderr}", file=sys.stderr)
            sys.exit(code)
            
        print(stdout)
        # Find created plots
        for p in args.out_dir.glob(f"*{plot_type}*.*"):
            if p.suffix in [".svg", ".png"]:
                generated_plots.append(p)
                
        # 4. Generate report if requested
        if args.report:
            build_markdown_report(title, source_desc, generated_plots, args.report)
            
    print(f"\n[Visualization Agent] SUCCESS: Scaffolded and verified {args.out_script.name}")


if __name__ == "__main__":
    main()
