"""Declared bounded support matrix for issue #83.

This module only *declares* rows. It states which option combinations the
validation attempts and which products each combination must produce. It does
not decide numerical acceptance: schedule equality is delegated verbatim to
``tools/compare_motioncorr.py --gate exact`` and motion truth to
``tools/run_known_motion_gates.py``. Those definitions are not redefined here.

Two axes are kept apart on purpose (issue #83 pass criteria):

* ``implementation`` coverage -- the option runs natively on CUDA, produces the
  complete declared product set with readable headers and metadata, and repeats
  / batches / resumes to identical pixels and metadata.
* ``numerical`` gates -- motion truth and CPU-agreement diagnostics. Those are
  reported by the existing tools under their own verdicts and are never implied
  by an implementation row passing.

EER and compressed decoding paths are deliberately absent: they remain issue #8.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional


#: Small declared fixtures, generated by ``test-data/generate_known_motion_fixture.py``.
#: Geometry mirrors each fixture's ground-truth JSON; it is re-read at run time
#: and a mismatch is a hard error rather than a silent assumption.
FIXTURES: Dict[str, Dict[str, object]] = {
    "km_global_hisnr": {"nx": 512, "ny": 512, "frames": 12, "angpix": 0.885,
                        "voltage": 300.0, "dose_per_frame": 1.277, "heavy": False},
    "km_local_hisnr": {"nx": 512, "ny": 512, "frames": 12, "angpix": 0.885,
                       "voltage": 300.0, "dose_per_frame": 1.277, "heavy": False},
    "km_local_nonsquare": {"nx": 768, "ny": 512, "frames": 12, "angpix": 0.885,
                           "voltage": 300.0, "dose_per_frame": 1.277, "heavy": False},
    "km_local_realscale": {"nx": 2048, "ny": 2048, "frames": 24, "angpix": 0.885,
                           "voltage": 300.0, "dose_per_frame": 1.277, "heavy": True},
}


@dataclass(frozen=True)
class Row:
    """One declared configuration of the support matrix."""

    row_id: str
    fixture: str
    #: Free-form axis labels, used only to group the published table.
    axes: Dict[str, str]
    #: Options appended to the common invocation, verbatim.
    args: List[str]
    #: Suffixes of the per-movie products this configuration must produce.
    #: ``""`` is the corrected average itself, ``.star`` the movie metadata.
    products: List[str] = field(default_factory=lambda: [".mrc", ".star"])
    #: Schedules compared against the uninterrupted run for exact equality.
    schedules: List[str] = field(default_factory=lambda: ["repeat", "batch", "resume"])
    #: Number of movies in the generated dataset for this row.
    n_movies: int = 3
    #: Set when the row is expected to fail the option validator instead of running.
    expect_reject: Optional[str] = None
    notes: str = ""


# Common invocation shared by every native row. ``--use_own`` selects the native
# implementation; ``--gpu`` selects CUDA and is added by the runner.
COMMON_ARGS = ["--use_own", "--j", "8", "--seed", "1", "--skip_logfile"]


def _dw(dose: float = 1.277) -> List[str]:
    return ["--dose_weighting", "--dose_per_frame", str(dose), "--voltage", "300"]


ROWS: List[Row] = [
    # ---------------------------------------------------------------- geometry
    Row("global_square", "km_global_hisnr",
        {"alignment": "global", "geometry": "square"},
        ["--patch_x", "1", "--patch_y", "1", "--skip_defect"]),
    Row("local_square", "km_local_hisnr",
        {"alignment": "local 4x4", "geometry": "square"},
        ["--patch_x", "4", "--patch_y", "4", "--skip_defect"]),
    Row("global_nonsquare", "km_local_nonsquare",
        {"alignment": "global", "geometry": "non-square 768x512"},
        ["--patch_x", "1", "--patch_y", "1", "--skip_defect"]),
    Row("local_nonsquare", "km_local_nonsquare",
        {"alignment": "local 4x4", "geometry": "non-square 768x512"},
        ["--patch_x", "4", "--patch_y", "4", "--skip_defect"]),

    # -------------------------------------------------------------------- gain
    Row("gain_none", "km_local_hisnr",
        {"gain": "absent"},
        ["--patch_x", "4", "--patch_y", "4", "--skip_defect"]),
    Row("gain_unity", "km_local_hisnr",
        {"gain": "unity MRC"},
        ["--patch_x", "4", "--patch_y", "4", "--skip_defect", "--gainref", "@GAIN_UNITY@"],
        notes="Unity gain must be numerically neutral; compared against gain_none as well."),
    Row("gain_nonunity", "km_local_hisnr",
        {"gain": "non-unity MRC"},
        ["--patch_x", "4", "--patch_y", "4", "--skip_defect", "--gainref", "@GAIN_NONUNITY@"]),

    # ------------------------------------------------------------------ defect
    Row("defect_skip", "km_local_hisnr",
        {"defect": "--skip_defect"},
        ["--patch_x", "4", "--patch_y", "4", "--skip_defect"]),
    Row("defect_detect", "km_local_hisnr",
        {"defect": "hot-pixel detection on"},
        ["--patch_x", "4", "--patch_y", "4"],
        notes="Exercises the seeded RNG defect path; seed pinned to 1."),
    Row("defect_file", "km_local_hisnr",
        {"defect": "MotionCor2 defect file"},
        ["--patch_x", "4", "--patch_y", "4", "--defect_file", "@DEFECT_FILE@"]),

    # -------------------------------------------------------------------- dose
    Row("dose_off", "km_local_hisnr",
        {"dose": "off"},
        ["--patch_x", "4", "--patch_y", "4", "--skip_defect"]),
    Row("dose_on", "km_local_hisnr",
        {"dose": "on"},
        ["--patch_x", "4", "--patch_y", "4", "--skip_defect"] + _dw()),
    Row("dose_on_savenoDW", "km_local_hisnr",
        {"dose": "on", "products": "saved noDW"},
        ["--patch_x", "4", "--patch_y", "4", "--skip_defect", "--save_noDW"] + _dw(),
        products=[".mrc", ".star", "_noDW.mrc"]),
    Row("dose_on_preexposure", "km_local_hisnr",
        {"dose": "on + pre-exposure"},
        ["--patch_x", "4", "--patch_y", "4", "--skip_defect", "--preexposure", "3.0"] + _dw(),
        notes="Pre-exposure association across resume is the #67 regression surface."),

    # ----------------------------------------------------------------- even/odd
    Row("evenodd", "km_local_hisnr",
        {"products": "even/odd split"},
        ["--patch_x", "4", "--patch_y", "4", "--skip_defect", "--even_odd_split"],
        products=[".mrc", ".star", "_EVN.mrc", "_ODD.mrc"]),
    Row("evenodd_dose_noDW", "km_local_hisnr",
        {"products": "even/odd + saved noDW", "dose": "on"},
        ["--patch_x", "4", "--patch_y", "4", "--skip_defect",
         "--even_odd_split", "--save_noDW"] + _dw(),
        products=[".mrc", ".star", "_noDW.mrc", "_EVN.mrc", "_ODD.mrc"],
        notes="EVN alone must not be accepted as completion (ADR66 sec.2)."),

    # -------------------------------------------------- frame selection/grouping
    Row("frames_subset", "km_local_hisnr",
        {"frames": "first 3 last 10"},
        ["--patch_x", "4", "--patch_y", "4", "--skip_defect",
         "--first_frame_sum", "3", "--last_frame_sum", "10"]),
    Row("group_frames_2", "km_local_hisnr",
        {"frames": "--group_frames 2"},
        ["--patch_x", "4", "--patch_y", "4", "--skip_defect", "--group_frames", "2"]),
    Row("group_frames_invalid", "km_local_hisnr",
        {"frames": "--group_frames 0"},
        ["--patch_x", "4", "--patch_y", "4", "--skip_defect", "--group_frames", "0"],
        schedules=[], expect_reject="group",
        notes="ADR66 sec.2 requires nonpositive grouping to be rejected by name."),
    Row("threads_invalid", "km_local_hisnr",
        {"options": "--j 0"},
        ["--patch_x", "4", "--patch_y", "4", "--skip_defect"],
        schedules=[], expect_reject="j",
        notes="Thread count 0; replaces --j in the common arguments."),

    # ----------------------------------------------------------------- binning
    Row("bin1", "km_local_hisnr",
        {"binning": "bin 1"},
        ["--patch_x", "4", "--patch_y", "4", "--skip_defect", "--bin_factor", "1"]),
    Row("early_bin2", "km_local_hisnr",
        {"binning": "early bin 2 (default)"},
        ["--patch_x", "4", "--patch_y", "4", "--skip_defect", "--bin_factor", "2"],
        notes="Compared only against itself across schedules, never against late binning."),
    Row("late_bin2", "km_local_hisnr",
        {"binning": "late bin 2 (--no_early_binning)"},
        ["--patch_x", "4", "--patch_y", "4", "--skip_defect",
         "--bin_factor", "2", "--no_early_binning"],
        notes="Compared only against itself across schedules, never against early binning."),

    # ----------------------------------------------------------- power spectrum
    Row("power_spectrum", "km_local_hisnr",
        {"products": "power spectrum"},
        ["--patch_x", "4", "--patch_y", "4", "--skip_defect",
         "--grouping_for_ps", "3", "--ps_size", "128"],
        products=[".mrc", ".star", "_PS.mrc"]),

    # --------------------------------------------------------------- real scale
    Row("realscale_local", "km_local_realscale",
        {"geometry": "2048x2048 real scale", "alignment": "local 5x5"},
        ["--patch_x", "5", "--patch_y", "5"] + _dw(),
        n_movies=2,
        notes="Heavy fixture; larger geometry row."),
]


#: Rows whose corrected pixels must additionally be identical to another row,
#: because the option is declared numerically neutral. Consumed by
#: ``run_matrix.check_cross_row_equalities``; a declared pair with no consumer
#: is itself a harness defect, since each row would then only ever be compared
#: against its own repeats and a uniformly wrong gain would look reproducible.
NEUTRAL_EQUIVALENCES = [("gain_unity", "gain_none")]

#: Pairs that must *differ*. Without these the equality above is satisfied by a
#: build that ignores ``--gainref`` entirely, which is exactly the regression
#: the neutrality claim is supposed to exclude. A control that cannot fail is
#: not evidence, so a pair recorded as equal here is an error.
NEUTRAL_NEGATIVE_CONTROLS = [
    ("gain_nonunity", "gain_none",
     "A non-unity multiplicative gain must change the corrected pixels. If it "
     "does not, --gainref is being ignored and gain_unity == gain_none above "
     "is vacuous."),
]


#: Coverage this matrix deliberately does not attempt, with where it belongs.
#: Published with the table so an unrun row is named rather than implied.
DEFERRED = [
    ("Process-shard schedules", "#53 / #55",
     "The multi-GPU scheduler is unmerged and #53 reports that "
     "`--gpu 0:1:2:3` silently uses a single device with movies run serially. "
     "Sharding is consumed only once that wrapper's aggregation is "
     "independently valid; no second scheduler is written here."),
    ("EER and compressed decoding paths", "#8",
     "Declared unsupported here until separately evidenced."),
    ("Broad allocation / plan / execution fault injection", "#69",
     "Only the single measured capacity datapoint below is in scope."),
    ("The CUDA resident-alignment fallback path", "#82 review / #69",
     "Not exercised. Review on PR #82 reports that the fallback at "
     "`motioncorr_runner.cpp:2019` retries without resetting "
     "`local_xshifts`/`local_yshifts`, so a retry would add onto an abandoned "
     "attempt. Nothing here triggers it: the measured peak was 1266 MiB of "
     "40960 on the largest declared row. A local row passing below is "
     "therefore not evidence about that path."),
    ("Optional CUDA event profiling", "#74", "Owned there."),
    ("Early-versus-late binning as an exact oracle", "#68",
     "Never compared that way. Each binning mode is compared only against "
     "itself across schedules."),
]


def rows_by_id() -> Dict[str, Row]:
    return {r.row_id: r for r in ROWS}


def declared_axes() -> Dict[str, List[str]]:
    """Axis -> declared values, for the published support table."""
    axes: Dict[str, List[str]] = {}
    for row in ROWS:
        for axis, value in row.axes.items():
            axes.setdefault(axis, [])
            if value not in axes[axis]:
                axes[axis].append(value)
    return axes
